name: hackathon24
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  get_it: ^8.0.0
  gap: ^3.0.1
  floating_bubbles: ^2.6.2
  animated_digit: ^3.2.3
  google_maps_flutter: ^2.9.0
  google_maps_flutter_web: ^0.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logo_invers.jpg
    - assets/kelag_ladestation.jpg
    - assets/ladestationen.json
    - assets/green-marker.png
    - assets/kaffee.jpg
    - assets/strom.jfif

