name: hackathon24
description: "An app to revolutionize ev loading at Kelag charging points"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  get_it: ^8.0.0
  gap: ^3.0.1
  floating_bubbles: ^2.6.2
  animated_digit: ^3.2.3
  google_maps_flutter: ^2.9.0
  google_maps_flutter_web: ^0.5.10
  flutter_multi_slider: ^2.0.1
  intl: ^0.19.0
  confetti: ^0.7.0
  http: ^1.2.2
  flutter_launcher_icons: ^0.14.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_spinkit: ^5.2.1
flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logo_invers.jpg
    - assets/kelag_ladestation.jpg
    - assets/ladestationen.json
    - assets/green-marker.png
    - assets/kaffee.jpg
    - assets/strom.jfif
    - assets/ngo/
    - assets/gamble/
    - assets/kelag_icon.png
flutter_launcher_icons:
  image_path: "assets/kelag_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/kelag_icon.png"
    background_color: "#009032"
    theme_color: "#009032"
  
