---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: hackathon
  labels:
    run: hackathon
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 32005
  selector:
    app: hackathon
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: hackathon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackathon
  template:
    metadata:
      labels:
        app: hackathon
    spec:
      containers:
        - name: python-app
          image: herrykun/hackathon24-python-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
      imagePullSecrets:
        - name: regcred
